on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: matsumonkie/izuna-action@6cda7ff356d87a9657ace0547a8a39a3dbe79130
      with:
        who-to-greet: 'io riiii'
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
